import { useState } from 'react'
import type { FormEvent } from 'react'
import './index.css'

type Mode = 'login' | 'register'
const empty = { studentId: '', studentPassword: '', captcha: '', username: '', password: '' }

export default function App() {
  const [mode, setMode] = useState<Mode>('login'); const [form, setForm] = useState(empty); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  const update = (key: keyof typeof empty) => (e: React.ChangeEvent<HTMLInputElement>) => setForm({ ...form, [key]: e.target.value })
  async function submit(e: FormEvent) { e.preventDefault(); setMessage(''); setBusy(true); const endpoint = mode === 'login' ? '/api/login' : '/api/register'; const body = mode === 'login' ? { username: form.username, password: form.password } : form; try { const r = await fetch(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await r.json(); if (!r.ok) throw new Error(data.error || '操作失败'); setMessage(mode === 'login' ? `登录成功，欢迎 ${data.username}` : '注册成功，现在可以使用本站账号登录启动器'); if (mode === 'register') setMode('login') } catch (err) { setMessage(err instanceof Error ? err.message : '操作失败') } finally { setBusy(false) } }
  return <main className="shell"><section className="hero"><div className="brand-mark">MC</div><p className="eyebrow">AUTHLIB-INJECTOR READY</p><h1>方块世界，<em>自由登录</em></h1><p className="intro">使用重庆邮电大学统一身份认证完成注册，然后用本站账号登录启动器。</p><div className="status"><span /> 服务运行正常</div></section><section className="panel"><div className="tabs"><button className={mode === 'login' ? 'active' : ''} onClick={() => { setMode('login'); setMessage('') }}>本站登录</button><button className={mode === 'register' ? 'active' : ''} onClick={() => { setMode('register'); setMessage('') }}>注册账号</button></div><form onSubmit={submit}>{mode === 'register' && <><label>重邮统一账号<input required inputMode="numeric" pattern="[0-9]+" value={form.studentId} onChange={update('studentId')} placeholder="学号 / 工号" /></label><label>统一账号密码<input required type="password" value={form.studentPassword} onChange={update('studentPassword')} placeholder="统一身份认证密码" /></label><label>验证码（如页面要求）<input value={form.captcha} onChange={update('captcha')} placeholder="没有验证码可留空" /></label></>}<label>本站用户名<input required pattern="[A-Za-z0-9]+" value={form.username} onChange={update('username')} placeholder="英文和数字" /></label><label>本站密码<input required minLength={6} type="password" value={form.password} onChange={update('password')} placeholder="至少 6 位" /></label><button className="submit" disabled={busy}>{busy ? '正在验证…' : mode === 'login' ? '登录启动器' : '验证并注册'}</button></form>{message && <p className="message">{message}</p>}<p className="fine">本站登录凭据与统一账号密码分开保存。启动器只能使用本站用户名和密码。</p></section></main>
}
